### PR TITLE
#162163277 Pagination support for articles

### PR DESCRIPTION
**Pull request by Nta1e**
**What does this PR do?**
This pull request delivers a feature that adds pagination support to articles

**Description of the tasks to be completed**
Reading can be a nightmare when we have so many articles, that's where pagination comes in.
Now only two articles are returned at a time for easy readability and the rest are moved 
to the next page.

**How can this be manually tested?**
Navigate to the endpoint for returning all articles ie `api/articles` and you should see the following result

screenshot 2018-12-19 at 19 47 40

### CODE REVIEW

**Review by joshtrigger — APPROVED** [review]
nice work

**Review by Kasulejoseph — APPROVED** [review]

**Comment by Kasulejoseph** [comment]
good work

**Review by KicaRonaldOkello — APPROVED** [review]

**Review by SokoPaulSokool — APPROVED** [review]
Cool

**Review by bibangamba — APPROVED** [review]

**Review by kafuuma — APPROVED** [review]

**Comment by Nta1e** [comment]
@collin5 Am done with limiting what is returned on a specific page ie 
`http://localhost:8000/api/articles?page=2&limit=3`

**Review by collin5 — CHANGES_REQUESTED** [review]
Nice! Can you please also add tests for this behavior.

**Comment by Nta1e** [comment]
@collin5 I am done writing the tests

**Review by kafuuma — APPROVED** [review]

**Review by collin5 — APPROVED** [review]

**Pull request merged**
