### PR TITLE
#162163279 User should be able to see article read time

### PR DESCRIPTION
**Pull request by joshtrigger**
**What does this PR do?**
this PR enables a user see the estimated time it will take to read a whole article

**Description of tasks**
Create an article using this api endpoint
**`POST`** `/api/articles/`

**How to manually test it**

- clone the repository

- install the dependencies in the requirements.txt file

- the **`POST`** `/api/articles/` should return data in this format:
```
{
    "article": {
        "title": "nineth article",
        "body": "this is my 9th article and im so proud of it because it took a lot of work to put down",
        "description": "testing readtime",
        "tagList": [
            "life"
        ],
        "author": {
            "username": "lugjosh",
            "bio": "",
            "image": "",
            "email": "lugjosh@gmail.com"
        },
        "slug": "nineth-article-936a7fa447cc",
        "published": false,
        "created_at": "2018-12-18T11:10:54.653838Z",
        "updated_at": "2018-12-18T11:10:54.653859Z",
        "favourited": false,
        "favouriteCount": 0,
        "readTime": 1,
        "images": [
            {
                "id": 10,
                "image_url": "https://url.com/",
                "description": "image is cool",
                "position_in_body_before": 1
            }
        ]
    }
}
```
including the `readTime` key

**What are the relevant pivotal tracker stories?**
#162163279

### CODE REVIEW

**Review by Kasulejoseph — APPROVED** [review]

**Comment by Kasulejoseph** [comment]
cool stuff

**Review by KicaRonaldOkello — APPROVED** [review]

**Review by Nta1e — APPROVED** [review]

**Review by SokoPaulSokool — APPROVED** [review]
Good work

**Review by bibangamba — APPROVED** [review]

**Review by kafuuma — APPROVED** [review]
We agreed not to push migrations

**Review by SokoPaulSokool — APPROVED** [review]

**Review by collin5 — CHANGES_REQUESTED** [review]
~~We should also take into account the images an article contains.~~

**Review by collin5 — APPROVED** [review]

**Pull request merged**
