### PR TITLE
#162163258 Setup and deploy base application to Heroku

### PR DESCRIPTION
**Pull request by bibangamba**
#### What does this PR do?
This pull request allows for Heroku deployment and enables creation of a review app on each pull request created

#### Description of tasks to be completed?
- Install gunicorn and add it to requirements.txt
- Add a Procfile to the root directory, contents will enable Heroku run the application
- Add app.json file that heroku uses to configure the review apps generated after a pull request

#### How should this be tested?
- Go to the [web app](https://ch-heroku-deploy-162163258.herokuapp.com) and  navigate to the [admin](https://ch-heroku-deploy-162163258.herokuapp.com/admin) page (since it's the only one that works currently)
- **Note** The review apps require the app.json file to be on the default branch (**develop**), if this pull request is merged to **develop**, all the open pull requests will have review apps created for them. This will be shown with a link added to the pull request pointing to the deployed review app.

#### What are the relevant pivotal tracker stories
#162163258

#### Screenshots

This screenshot shows the working **/admin** page of the deployed app
image

This screenshot shows the pipeline and the different environments. **ah-backend-athena-staging** (STAGING) deploys from the **develop** branch while **ah-backend-athena** (PRODUCTION) deploys from the **master** branch
image

### CODE REVIEW

**Comment by Kasulejoseph** [comment]
Awesome.. thanks for the good work

**Review by Kasulejoseph — APPROVED** [review]

**Comment by Nta1e** [comment]
_Good work_

**Review by Nta1e — APPROVED** [review]

**Review by kafuuma — APPROVED** [review]
Good work andrew
Put the link to the heroku app in the Readme file also

**Comment by joshtrigger** [comment]
great work andrew

**Review by joshtrigger — APPROVED** [review]

**Review by KicaRonaldOkello — APPROVED** [review]

**Review by collin5 — APPROVED** [review]

**Pull request merged**
