### PR TITLE
#162163275 List Users 

### PR DESCRIPTION
**Pull request by KicaRonaldOkello**
**What does this PR do?**
This PR ensures that an admin user can return a list and profiles of existing users.

**Description of Task to be completed**

- A logged in admin can return a list and profiles of existing users.

**Endpoint working**
-`GET /api/profiles/`

**How should this be manually tested?**

- Clone repository.

- create virtual environment

- Install requirements pip install -r requirements.txt - Run the project python manage.py runserver

- Paste URL in postman: http://localhost:8000/api/profiles/

**What are the relevant pivotal tracker stories?**
 #162163275
Screenshots:
image

### CODE REVIEW

**Review by collin5 — CHANGES_REQUESTED** [review]
Looks good. Though I think this should be restricted for only `admin`.

**Review by bibangamba — APPROVED** [review]

**Review by Kasulejoseph — APPROVED** [review]

**Comment by KicaRonaldOkello** [comment]
collin5, I have implemented the changes that you recommended

**Review by Nta1e — APPROVED** [review]

**Review by collin5 — CHANGES_REQUESTED** [review]
Great work! Just one more thing. Add assert for a `403` if a non-admin user tries accessing the endpoint.

**Comment by KicaRonaldOkello** [comment]
I have done it

**Review by collin5 — APPROVED** [review]

**Pull request merged**
