### PR TITLE
#162163271 Ft articles like dislike

### PR DESCRIPTION
**Pull request by SokoPaulSokool**
### What does this PR do?
This pull request enables one to like and dislike an article

### Description of tasks to be completed?
- writing unit tests for this feature
- Have these endpoints working
- POST /api/articles/:slug/like/
- DELETE /api/articles/:slug/like/

### How should this be tested?
Clone the repo,
- Install the requirements with pip install -r requirements.txt
- To run tests, run ./manage.py test
- Run python manage.py runserver
- Test the endpoints in postman

### Like an article
Create an article and obtain its slug
Replace the slug in POST /api/articles/:slug/like/ and send a POST request

### Dislike an article
Create an article and obtain its slug
Replace the slug in  /api/articles/:slug/like/ and send a DELETE request

### CODE REVIEW

**Review by joshtrigger — APPROVED** [review]

**Comment by KicaRonaldOkello** [comment]
Is it possible for you to squash the commits?

**Comment by Kasulejoseph** [comment]
@SokoPaulSokool please resolve the conflicts

**Review by kafuuma — APPROVED** [review]
Resolve conflicts

**Comment by SokoPaulSokool** [comment]
Conflicts have been resolved

**Review by collin5 — APPROVED** [review]

**Pull request merged**
